"""empty message

Revision ID: 0b0c8c0c3908
Revises: e72e855c52c2
Create Date: 2023-11-14 04:37:10.421524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b0c8c0c3908'
down_revision = 'e72e855c52c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopping_cart_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'shopping_carts', ['shopping_cart_id'], ['id'])

    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('Active', 'Inactive', 'Pending', name='status'), autoincrement=False, nullable=False))

    with op.batch_alter_table('shopping_cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shopping_cart_id')

    # ### end Alembic commands ###
