"""empty message

Revision ID: ecca81036133
Revises: 36d71b917b73
Create Date: 2023-11-16 03:43:58.595694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecca81036133'
down_revision = '36d71b917b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'bills', ['bill_id'], ['id'])

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint('bills_shopping_cart_id_fkey', type_='foreignkey')
        batch_op.drop_column('shopping_cart_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopping_cart_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('bills_shopping_cart_id_fkey', 'shopping_carts', ['shopping_cart_id'], ['id'])

    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
